wrangler.toml


name = "leverageai-portfolio"
compatibility_date = "2024-09-16"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "leverageai-portfolio"
route = { pattern = "leverageai.com/api/*", zone_name = "leverageai.com" }

[[env.production.kv_namespaces]]
binding = "PORTFOLIO_KV"
id = "your_production_kv_namespace_id"

[[env.production.kv_namespaces]]
binding = "CONTACTS_KV"
id = "your_production_contacts_kv_namespace_id"

[env.staging]
name = "leverageai-portfolio-staging"
route = { pattern = "staging.leverageai.com/api/*", zone_name = "leverageai.com" }

[[env.staging.kv_namespaces]]
binding = "PORTFOLIO_KV"
id = "your_staging_kv_namespace_id"

[[env.staging.kv_namespaces]]
binding = "CONTACTS_KV"
id = "your_staging_contacts_kv_namespace_id"

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"